name: .NET 6 CI

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
  workflow_dispatch:

concurrency:
  group: dotnet-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    uses: trippwill/monkey/.github/workflows/ci-call.yml@main
    with:
      runs-on: ubuntu-latest
      dotnet-version: 6.0.x
      dotnet-include-prerelease: true
    secrets:
      FEEDUSER: ${{ secrets.FEEDUSER }}
      FEEDKEY: ${{ secrets.FEEDKEY }}
  build-windows:
    uses: trippwill/monkey/.github/workflows/ci-call.yml@main
    with:
      runs-on: ubuntu-latest
      dotnet-version: 6.0.x
      dotnet-include-prerelease: true
    secrets:
      FEEDUSER: ${{ secrets.FEEDUSER }}
      FEEDKEY: ${{ secrets.FEEDKEY }}
  build-macos:
    uses: trippwill/monkey/.github/workflows/ci-call.yml@main
    with:
      runs-on: ubuntu-latest
      dotnet-version: 6.0.x
      dotnet-include-prerelease: true
    secrets:
      FEEDUSER: ${{ secrets.FEEDUSER }}
      FEEDKEY: ${{ secrets.FEEDKEY }}
